"""Icons and border sets for shinyshell."""

_ICONS = {
    "success": "✨",
    "error": "💥",
    "warning": "⚠️",
    "info": "ℹ️",
    "question": "❓",
    "star": "⭐",
    "heart": "💜",
    "fire": "🔥",
    "rocket": "🚀",
    "check": "✅",
    "cross": "❌",
    "arrow": "→",
    "bullet": "•",
    "diamond": "◆",
    "pointer": "▸",
    "dot": "·",
    "lightning": "⚡",
    "clock": "🕐",
    "lock": "🔒",
    "unlock": "🔓",
    "key": "🔑",
    "gear": "⚙️",
    "package": "📦",
    "link": "🔗",
    "globe": "🌍",
    "mail": "📧",
    "phone": "📞",
    "pin": "📌",
    "bookmark": "🔖",
    "tag": "🏷️",
    "flag": "🚩",
    "target": "🎯",
    "trophy": "🏆",
    "medal": "🥇",
    "gift": "🎁",
    "party": "🎉",
    "sparkles": "✨",
    "magic": "🪄",
    "robot": "🤖",
    "bug": "🐛",
    "eyes": "👀",
    "brain": "🧠",
    "tools": "🛠️",
    "chart": "📊",
    "database": "🗄️",
    "file": "📄",
    "folder": "📁",
    "download": "📥",
    "upload": "📤",
    "save": "💾",
    "print": "🖨️",
    "search": "🔍",
    "shield": "🛡️",
    "money": "💰",
    "credit": "💳",
    "shopping": "🛒",
    "home": "🏠",
    "world": "🌐",
    "mobile": "📱",
    "desktop": "🖥️",
    "server": "🖥",
    "cloud": "☁️",
    "terminal": "💻",
}

_BORDERS = {
    "single": "─│┌┐└┘├┤┬┴┼",
    "double": "═║╔╗╚╝╠╣╦╩╬",
    "round": "─│╭╮╰╯├┤┬┴┼",
    "bold": "━┃┏┓┗┛┣┫┳┻╋",
    "dashed": "┄┆┌┐└┘├┤┬┴┼",
    "none": "       ",
}
